name: Auto-Sync AI Logs

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Generate AI Log and Push to GitHub
        run: |
          python scripts/generate_log.py
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add logs/
          git commit -m "Auto-sync AI log - $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push

      - name: Sync Logs to Notion
        run: python scripts/sync_to_notion.py
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
