name: DeepSeek Log Analysis

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM
  workflow_dispatch:  # Allows manual trigger

jobs:
  analyze_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests openai  # Add DeepSeek API if needed

      - name: Run DeepSeek Analysis
        run: python scripts/deepseek_analysis.py
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
